import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const externalCalendars = pgTable("external_calendars", {
  id: uuid("id").defaultRandom().primaryKey(),
  displayName: text("display_name").notNull(),
  provider: text("provider").notNull(), // google | yandex | ics
  syncEnabled: boolean("sync_enabled").notNull().default(true),
  authData: jsonb("auth_data"), // tokens / url (encrypted at rest)
  lastSyncAt: timestamp("last_sync_at", { mode: "string", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const externalEvents = pgTable("external_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  calendarId: uuid("calendar_id").notNull(),
  uid: text("uid").notNull(),
  title: text("title").notNull(),
  startTime: timestamp("start_time", { mode: "string", withTimezone: true }).notNull(),
  endTime: timestamp("end_time", { mode: "string", withTimezone: true }).notNull(),
  allDay: boolean("all_day").notNull().default(false),
  linkedMeetingId: uuid("linked_meeting_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const externalCalendarRelations = relations(externalCalendars, ({ many }) => ({
  events: many(externalEvents),
}));

export type ExternalCalendarRow = typeof externalCalendars.$inferSelect;
export type ExternalEventRow = typeof externalEvents.$inferSelect;
export type ExternalCalendarInsert = typeof externalCalendars.$inferInsert;
export type ExternalEventInsert = typeof externalEvents.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
