import { pgTable, uuid, text, timestamp, boolean, jsonb } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const externalCalendars = pgTable("external_calendars", {
  id: uuid("id").defaultRandom().primaryKey(),
  displayName: text("display_name").notNull(),
  provider: text("provider").notNull(), // google | yandex | ics
  syncEnabled: boolean("sync_enabled").notNull().default(true),
  authData: jsonb("auth_data"), // tokens / url (encrypted at rest)
  lastSyncAt: timestamp("last_sync_at", { mode: "string", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const externalEvents = pgTable("external_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  externalCalendarId: uuid("external_calendar_id").notNull(),
  externalEventId: text("external_event_id").notNull(),
  summary: text("summary"),
  description: text("description"),
  startTime: text("start_time"),
  endTime: text("end_time"),
  recurrenceRule: text("recurrence_rule"),
  location: text("location"),
  linkedMeetingId: uuid("linked_meeting_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const processedEvents = pgTable("processed_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  eventId: text("event_id").notNull().unique(),
  eventType: text("event_type").notNull(),
  processedAt: timestamp("processed_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const externalCalendarRelations = relations(externalCalendars, ({ many }) => ({
  events: many(externalEvents),
}));

export type ExternalCalendarRow = typeof externalCalendars.$inferSelect;
export type ExternalEventRow = typeof externalEvents.$inferSelect;
export type ExternalCalendarInsert = typeof externalCalendars.$inferInsert;
export type ExternalEventInsert = typeof externalEvents.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
