import { pgTable, uuid, text, timestamp, jsonb, uniqueIndex } from "drizzle-orm/pg-core";

export const projects = pgTable("projects", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  goal: text("goal"),
  status: text("status").notNull().default("active"), // active | archived | completed
  profileIds: uuid("profile_ids").array().notNull().default([]),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

// Event-driven project dashboard index (migration 0002): one row per linked
// entity (note/task/meeting/file). Built by subscribing to pmos.* events.
export const projectItems = pgTable("project_items", {
  id: uuid("id").defaultRandom().primaryKey(),
  projectId: uuid("project_id").notNull(),
  entityType: text("entity_type").notNull(), // note | task | meeting | file
  entityId: uuid("entity_id").notNull(),
  title: text("title"),
  startDate: text("start_date"),
  status: text("status"),
  payload: jsonb("payload").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectEntityIdx: uniqueIndex("project_items_project_entity_idx").on(t.projectId, t.entityType, t.entityId),
}));

// Event idempotency ledger (SAGA.md): stores event ids already processed.
export const processedEvents = pgTable("processed_events", {
  eventId: uuid("event_id").primaryKey(),
  processedAt: timestamp("processed_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type ProjectRow = typeof projects.$inferSelect;
export type ProjectInsert = typeof projects.$inferInsert;
export type ProjectItemRow = typeof projectItems.$inferSelect;
export type ProjectItemInsert = typeof projectItems.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
