import { buildApp } from "./dist/app.js";
const app = await buildApp();
await app.listen({ port: 4123, host: "127.0.0.1" });
const base = "http://127.0.0.1:4123/api/calendar/v1";
const cr = await fetch(base+"/meetings", {method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify({title:"Temp",startTime:"2026-08-02T09:00:00Z",endTime:"2026-08-02T09:15:00Z"})});
const id = (await cr.json()).id;
console.log("create", cr.statusCode, id);
const del = await fetch(base+"/meetings/"+id, {method:"DELETE"});
console.log("delete", del.statusCode);
const gt = await fetch(base+"/meetings/"+id);
console.log("get-after-delete", gt.statusCode);
await app.close();
