import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const imapAccounts = pgTable("imap_accounts", {
  id: uuid("id").defaultRandom().primaryKey(),
  host: text("host").notNull(),
  port: integer("port").notNull().default(993),
  ssl: boolean("ssl").notNull().default(true),
  username: text("username").notNull(),
  encryptedPassword: text("encrypted_password").notNull(),
  syncEnabled: boolean("sync_enabled").notNull().default(true),
  lastSyncAt: timestamp("last_sync_at", { mode: "string", withTimezone: true }),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const emails = pgTable("emails", {
  id: uuid("id").defaultRandom().primaryKey(),
  accountId: uuid("account_id").notNull(),
  messageId: text("message_id").notNull(),
  from: text("from").notNull(),
  subject: text("subject"),
  body: text("body"),
  receivedAt: timestamp("received_at", { mode: "string", withTimezone: true }),
  isArchived: boolean("is_archived").notNull().default(false),
  convertedNoteId: uuid("converted_note_id"),
  convertedTaskId: uuid("converted_task_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const emailRelations = relations(imapAccounts, ({ many }) => ({
  emails: many(emails),
}));

export type ImapAccountRow = typeof imapAccounts.$inferSelect;
export type EmailRow = typeof emails.$inferSelect;
export type ImapAccountInsert = typeof imapAccounts.$inferInsert;
export type EmailInsert = typeof emails.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
