import { pgTable, uuid, text, timestamp, jsonb, vector, uniqueIndex } from "drizzle-orm/pg-core";

// pgvector embedding table. Requires 'vector' extension in Postgres (docker-compose enables it).
export const embeddings = pgTable("embeddings", {
  id: uuid("id").defaultRandom().primaryKey(),
  entityType: text("entity_type").notNull(), // note | task | meeting | file
  entityId: uuid("entity_id").notNull(),
  content: text("content").notNull(),
  // nullable — Ollama may be down, rows must still be insertable (migration 0002)
  embedding: vector("embedding", { dimensions: 1536 }),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  // extra searchable data carried by source events (tags, linked projectId, ...)
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  // idempotent upserts keyed by source entity (migration 0002)
  entityIdx: uniqueIndex("embeddings_entity_idx").on(t.entityType, t.entityId),
}));

// Event idempotency ledger (SAGA.md): stores event ids already processed.
export const processedEvents = pgTable("processed_events", {
  eventId: uuid("event_id").primaryKey(),
  processedAt: timestamp("processed_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type EmbeddingRow = typeof embeddings.$inferSelect;
export type EmbeddingInsert = typeof embeddings.$inferInsert;
export type ProcessedEventRow = typeof processedEvents.$inferSelect;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
