import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const fileMeta = pgTable("file_meta", {
  id: uuid("id").defaultRandom().primaryKey(),
  filename: text("filename").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull().default(0),
  ownerType: text("owner_type"), // note | task | project | null
  ownerId: uuid("owner_id"),
  storagePath: text("storage_path").notNull(),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
});

export type FileMetaRow = typeof fileMeta.$inferSelect;
export type FileMetaInsert = typeof fileMeta.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
