import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const syncFolders = pgTable("sync_folders", {
  id: uuid("id").defaultRandom().primaryKey(),
  path: text("path").notNull(),
  autoImport: boolean("auto_import").notNull().default(false),
  autoExport: boolean("auto_export").notNull().default(false),
  profileScope: jsonb("profile_scope").notNull().default([]), // array of profile ids
  lastScanAt: timestamp("last_scan_at", { mode: "string", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type SyncFolderRow = typeof syncFolders.$inferSelect;
export type SyncFolderInsert = typeof syncFolders.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
