#!/usr/bin/env node
/**
 * gen-schemas.mjs — generates full Drizzle ORM schemas for the 14 remaining PMOS services.
 * Already-authored samples: services/notes (notes/templates/note_links),
 * services/tasks (tasks/task_dependencies). This script covers the rest, matching
 * FEATURES.md entities + ADR-004 schema-per-service isolation (cross-service refs are UUIDs only).
 * Idempotent: overwrites each service's src/db/schema.ts.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Common column builders (keep style identical to notes/tasks samples).
const HEADER = `import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
`;

const footer = (relExports = "") =>
  (relExports ? `\n${relExports}\n` : "\n") +
  "// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.\n";

// ---- profiles (ADR-004: profiles_) ----
function profiles() {
  return HEADER + `
export const profiles = pgTable("profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  color: text("color").notNull().default("#888888"),
  description: text("description"),
  isDefault: boolean("is_default").notNull().default(false),
  avatarUrl: text("avatar_url"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type ProfileRow = typeof profiles.$inferSelect;
export type ProfileInsert = typeof profiles.$inferInsert;
` + footer();
}

// ---- settings (key-value Shared Kernel, ADR-004: settings_) ----
function settings() {
  return HEADER + `
export const settings = pgTable("settings", {
  key: text("key").primaryKey(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type SettingRow = typeof settings.$inferSelect;
export type SettingInsert = typeof settings.$inferInsert;
` + footer();
}

// ---- calendar (meetings, reminders; ADR-004: calendar_) ----
function calendar() {
  return HEADER + `
export const meetings = pgTable("meetings", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  startTime: timestamp("start_time", { mode: "string", withTimezone: true }).notNull(),
  endTime: timestamp("end_time", { mode: "string", withTimezone: true }).notNull(),
  allDay: boolean("all_day").notNull().default(false),
  description: text("description"),
  location: text("location"),
  recurrence: text("recurrence"), // RFC5545 RRULE
  linkedProjectId: uuid("linked_project_id"),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  linkedExternalEventId: uuid("linked_external_event_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const reminders = pgTable("reminders", {
  id: uuid("id").defaultRandom().primaryKey(),
  meetingId: uuid("meeting_id").notNull(),
  remindAt: timestamp("remind_at", { mode: "string", withTimezone: true }).notNull(),
  channel: text("channel").notNull().default("push"), // push | email
  sent: boolean("sent").notNull().default(false),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const calendarRelations = relations(meetings, ({ many }) => ({
  reminders: many(reminders),
}));

export type MeetingRow = typeof meetings.$inferSelect;
export type MeetingInsert = typeof meetings.$inferInsert;
export type ReminderRow = typeof reminders.$inferSelect;
` + footer();
}

// ---- projects (ADR-004: projects_) ----
function projects() {
  return HEADER + `
export const projects = pgTable("projects", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  goal: text("goal"),
  status: text("status").notNull().default("active"), // active | archived | completed
  profileIds: uuid("profile_ids").array().notNull().default([]),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type ProjectRow = typeof projects.$inferSelect;
export type ProjectInsert = typeof projects.$inferInsert;
` + footer();
}

// ---- files (file_meta; ADR-004: files_) ----
function files() {
  return HEADER + `
export const fileMeta = pgTable("file_meta", {
  id: uuid("id").defaultRandom().primaryKey(),
  filename: text("filename").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull().default(0),
  ownerType: text("owner_type"), // note | task | project | null
  ownerId: uuid("owner_id"),
  storagePath: text("storage_path").notNull(),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  uploadedAt: timestamp("uploaded_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type FileMetaRow = typeof fileMeta.$inferSelect;
export type FileMetaInsert = typeof fileMeta.$inferInsert;
` + footer();
}

// ---- search-rag (embeddings, pgvector; ADR-004: search_rag_) ----
function searchRag() {
  return HEADER + `
// pgvector embedding table. Requires 'vector' extension in Postgres (docker-compose enables it).
export const embeddings = pgTable("embeddings", {
  id: uuid("id").defaultRandom().primaryKey(),
  entityType: text("entity_type").notNull(), // note | task | meeting | file
  entityId: uuid("entity_id").notNull(),
  content: text("content").notNull(),
  embedding: vector("embedding", { dimensions: 1536 }).notNull(),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type EmbeddingRow = typeof embeddings.$inferSelect;
export type EmbeddingInsert = typeof embeddings.$inferInsert;
` + footer();
}

// ---- ai-gateway (stateless proxy; ADR-004: no persistent tables required) ----
function aiGateway() {
  return HEADER + `
// ai-gateway is a stateless LLM proxy. This table logs requests for observability only.
export const aiRequestLog = pgTable("ai_request_log", {
  id: uuid("id").defaultRandom().primaryKey(),
  kind: text("kind").notNull(), // restore_punctuation | dictate
  model: text("model"),
  promptChars: integer("prompt_chars").notNull().default(0),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type AiRequestLogRow = typeof aiRequestLog.$inferSelect;
export type AiRequestLogInsert = typeof aiRequestLog.$inferInsert;
` + footer();
}

// ---- agent (agent_messages; FEATURES §10) ----
function agent() {
  return HEADER + `
export const agentMessages = pgTable("agent_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  type: text("type").notNull(), // digest | trigger | suggestion
  source: text("source"), // originating event, e.g. tasks.status_changed
  status: text("status").notNull().default("pending"), // pending | accepted | dismissed
  actions: jsonb("actions").notNull().default([]), // suggested actions
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type AgentMessageRow = typeof agentMessages.$inferSelect;
export type AgentMessageInsert = typeof agentMessages.$inferInsert;
` + footer();
}

// ---- email (imap_accounts, emails; FEATURES §11) ----
function email() {
  return HEADER + `
export const imapAccounts = pgTable("imap_accounts", {
  id: uuid("id").defaultRandom().primaryKey(),
  host: text("host").notNull(),
  port: integer("port").notNull().default(993),
  ssl: boolean("ssl").notNull().default(true),
  username: text("username").notNull(),
  encryptedPassword: text("encrypted_password").notNull(),
  syncEnabled: boolean("sync_enabled").notNull().default(true),
  lastSyncAt: timestamp("last_sync_at", { mode: "string", withTimezone: true }),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const emails = pgTable("emails", {
  id: uuid("id").defaultRandom().primaryKey(),
  accountId: uuid("account_id").notNull(),
  messageId: text("message_id").notNull(),
  from: text("from").notNull(),
  subject: text("subject"),
  body: text("body"),
  receivedAt: timestamp("received_at", { mode: "string", withTimezone: true }),
  isArchived: boolean("is_archived").notNull().default(false),
  convertedNoteId: uuid("converted_note_id"),
  convertedTaskId: uuid("converted_task_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const emailRelations = relations(imapAccounts, ({ many }) => ({
  emails: many(emails),
}));

export type ImapAccountRow = typeof imapAccounts.$inferSelect;
export type EmailRow = typeof emails.$inferSelect;
export type ImapAccountInsert = typeof imapAccounts.$inferInsert;
export type EmailInsert = typeof emails.$inferInsert;
` + footer();
}

// ---- external-calendars (external_calendars, external_events; FEATURES §12) ----
function externalCalendars() {
  return HEADER + `
export const externalCalendars = pgTable("external_calendars", {
  id: uuid("id").defaultRandom().primaryKey(),
  displayName: text("display_name").notNull(),
  provider: text("provider").notNull(), // google | yandex | ics
  syncEnabled: boolean("sync_enabled").notNull().default(true),
  authData: jsonb("auth_data"), // tokens / url (encrypted at rest)
  lastSyncAt: timestamp("last_sync_at", { mode: "string", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const externalEvents = pgTable("external_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  calendarId: uuid("calendar_id").notNull(),
  uid: text("uid").notNull(),
  title: text("title").notNull(),
  startTime: timestamp("start_time", { mode: "string", withTimezone: true }).notNull(),
  endTime: timestamp("end_time", { mode: "string", withTimezone: true }).notNull(),
  allDay: boolean("all_day").notNull().default(false),
  linkedMeetingId: uuid("linked_meeting_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const externalCalendarRelations = relations(externalCalendars, ({ many }) => ({
  events: many(externalEvents),
}));

export type ExternalCalendarRow = typeof externalCalendars.$inferSelect;
export type ExternalEventRow = typeof externalEvents.$inferSelect;
export type ExternalCalendarInsert = typeof externalCalendars.$inferInsert;
export type ExternalEventInsert = typeof externalEvents.$inferInsert;
` + footer();
}

// ---- integrations (api_keys, webhooks, webhook_deliveries; FEATURES §13) ----
function integrations() {
  return HEADER + `
export const apiKeys = pgTable("api_keys", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  keyHash: text("key_hash").notNull(), // SHA256 of the plaintext key
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const webhooks = pgTable("webhooks", {
  id: uuid("id").defaultRandom().primaryKey(),
  url: text("url").notNull(),
  events: text("events").array().notNull().default([]),
  secret: text("secret"),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const webhookDeliveries = pgTable("webhook_deliveries", {
  id: uuid("id").defaultRandom().primaryKey(),
  webhookId: uuid("webhook_id").notNull(),
  eventType: text("event_type").notNull(),
  payload: jsonb("payload"),
  status: text("status").notNull().default("pending"), // pending | sent | failed | dead
  attempt: integer("attempt").notNull().default(0),
  nextRetryAt: timestamp("next_retry_at", { mode: "string", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const webhookRelations = relations(webhooks, ({ many }) => ({
  deliveries: many(webhookDeliveries),
}));

export type ApiKeyRow = typeof apiKeys.$inferSelect;
export type WebhookRow = typeof webhooks.$inferSelect;
export type WebhookDeliveryRow = typeof webhookDeliveries.$inferSelect;
export type ApiKeyInsert = typeof apiKeys.$inferInsert;
export type WebhookInsert = typeof webhooks.$inferInsert;
` + footer();
}

// ---- time-tracking (timesheet, pomodoro_sessions; FEATURES §14) ----
function timeTracking() {
  return HEADER + `
export const timesheet = pgTable("timesheet", {
  id: uuid("id").defaultRandom().primaryKey(),
  taskId: uuid("task_id"),
  description: text("description"),
  startedAt: timestamp("started_at", { mode: "string", withTimezone: true }).notNull(),
  endedAt: timestamp("ended_at", { mode: "string", withTimezone: true }),
  durationSec: integer("duration_sec"),
  profileIds: uuid("profile_ids").array().notNull().default([]),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const pomodoroSessions = pgTable("pomodoro_sessions", {
  id: uuid("id").defaultRandom().primaryKey(),
  mode: text("mode").notNull(), // pomodoro | flowtime | countdown
  startedAt: timestamp("started_at", { mode: "string", withTimezone: true }).notNull(),
  endedAt: timestamp("ended_at", { mode: "string", withTimezone: true }),
  plannedMin: integer("planned_min"),
  completed: boolean("completed").notNull().default(false),
  taskId: uuid("task_id"),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type TimesheetRow = typeof timesheet.$inferSelect;
export type PomodoroRow = typeof pomodoroSessions.$inferSelect;
export type TimesheetInsert = typeof timesheet.$inferInsert;
export type PomodoroInsert = typeof pomodoroSessions.$inferInsert;
` + footer();
}

// ---- export-import (export_jobs; FEATURES §15) ----
function exportImport() {
  return HEADER + `
export const exportJobs = pgTable("export_jobs", {
  id: uuid("id").defaultRandom().primaryKey(),
  kind: text("kind").notNull().default("full"), // full | partial
  status: text("status").notNull().default("pending"), // pending | done | failed
  filePath: text("file_path"),
  size: integer("size").default(0),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type ExportJobRow = typeof exportJobs.$inferSelect;
export type ExportJobInsert = typeof exportJobs.$inferInsert;
` + footer();
}

// ---- sync (sync_folders; FEATURES §16) ----
function sync() {
  return HEADER + `
export const syncFolders = pgTable("sync_folders", {
  id: uuid("id").defaultRandom().primaryKey(),
  path: text("path").notNull(),
  autoImport: boolean("auto_import").notNull().default(false),
  autoExport: boolean("auto_export").notNull().default(false),
  profileScope: jsonb("profile_scope").notNull().default([]), // array of profile ids
  lastScanAt: timestamp("last_scan_at", { mode: "string", withTimezone: true }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type SyncFolderRow = typeof syncFolders.$inferSelect;
export type SyncFolderInsert = typeof syncFolders.$inferInsert;
` + footer();
}

// service -> generator
const GEN = {
  profiles,
  settings,
  calendar,
  projects,
  files,
  "search-rag": searchRag,
  "ai-gateway": aiGateway,
  agent,
  email,
  "external-calendars": externalCalendars,
  integrations,
  "time-tracking": timeTracking,
  "export-import": exportImport,
  sync,
};

let count = 0;
for (const [name, gen] of Object.entries(GEN)) {
  const target = join(ROOT, "services", name, "src", "db", "schema.ts");
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, gen());
  count++;
}
console.log(`Generated full Drizzle schemas for ${count} services.`);
