import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey, unique } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const exportJobs = pgTable("export_jobs", {
  id: uuid("id").defaultRandom().primaryKey(),
  kind: text("kind").notNull().default("full"), // full | export (ZIP export) | partial
  status: text("status").notNull().default("pending"), // pending | completed | failed
  filePath: text("file_path"),
  size: integer("size").default(0),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

// Event-driven read model: latest payload per (entity_type, entity_id), fed by
// pmos.* events. GET /export streams this table into the ZIP archive.
export const exportStore = pgTable("export_store", {
  id: uuid("id").defaultRandom().primaryKey(),
  entityType: text("entity_type").notNull(), // notes | tasks | meetings | ...
  entityId: text("entity_id").notNull(), // data.id (or data.<x>Id) from the event
  payload: jsonb("payload"), // full event data
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }),
}, (t) => ({ unique: unique("export_store_entity_type_entity_id_unique").on(t.entityType, t.entityId) }));

// Durable log of imported entries (kind: note/task/...). Actual delivery to the
// target services happens later via events — these rows are the durable record.
export const importItems = pgTable("import_items", {
  id: uuid("id").defaultRandom().primaryKey(),
  kind: text("kind").notNull(), // note | task | meeting | ...
  title: text("title"),
  content: text("content"),
  status: text("status").notNull().default("imported"), // imported
  importedAt: timestamp("imported_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

// Idempotency ledger (SAGA.md / events.yaml): subscribers check event.id here
// before upserting export_store so at-least-once NATS delivery never double-processes.
export const processedEvents = pgTable("processed_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  eventId: text("event_id").notNull().unique(),
  eventType: text("event_type"),
  processedAt: timestamp("processed_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type ExportJobRow = typeof exportJobs.$inferSelect;
export type ExportStoreRow = typeof exportStore.$inferSelect;
export type ImportItemRow = typeof importItems.$inferSelect;
export type ExportJobInsert = typeof exportJobs.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
