import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const agentMessages = pgTable("agent_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  type: text("type").notNull(), // digest | trigger | suggestion
  source: text("source"), // originating event, e.g. tasks.status_changed
  status: text("status").notNull().default("pending"), // pending | accepted | dismissed
  actions: jsonb("actions").notNull().default([]), // suggested actions
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type AgentMessageRow = typeof agentMessages.$inferSelect;
export type AgentMessageInsert = typeof agentMessages.$inferInsert;

// Idempotency ledger for inbound events (SAGA.md): event.id → processed.
export const processedEvents = pgTable("processed_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  eventId: text("event_id").notNull().unique(),
  eventType: text("event_type").notNull(),
  processedAt: timestamp("processed_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type ProcessedEventRow = typeof processedEvents.$inferSelect;
export type ProcessedEventInsert = typeof processedEvents.$inferInsert;

// Digest cache fed by inbound events (meetings.created, tasks.status_changed).
// The agent never reads other services' DBs — only its own read model (ADR-003).
export const dailyEvents = pgTable("daily_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  kind: text("kind").notNull(), // meeting | task | ...
  title: text("title"),
  startTime: text("start_time"), // ISO string (meeting start / task deadline)
  data: jsonb("data").notNull().default({}), // full event payload
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type DailyEventRow = typeof dailyEvents.$inferSelect;
export type DailyEventInsert = typeof dailyEvents.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
