import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const agentMessages = pgTable("agent_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  type: text("type").notNull(), // digest | trigger | suggestion
  source: text("source"), // originating event, e.g. tasks.status_changed
  status: text("status").notNull().default("pending"), // pending | accepted | dismissed
  actions: jsonb("actions").notNull().default([]), // suggested actions
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type AgentMessageRow = typeof agentMessages.$inferSelect;
export type AgentMessageInsert = typeof agentMessages.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
