import { pgTable, uuid, text, timestamp, boolean, integer, jsonb, vector, primaryKey } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ai-gateway is a stateless LLM proxy. This table logs requests for observability only.
export const aiRequestLog = pgTable("ai_request_log", {
  id: uuid("id").defaultRandom().primaryKey(),
  kind: text("kind").notNull(), // restore_punctuation | dictate
  model: text("model"),
  promptChars: integer("prompt_chars").notNull().default(0),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export type AiRequestLogRow = typeof aiRequestLog.$inferSelect;
export type AiRequestLogInsert = typeof aiRequestLog.$inferInsert;

// Generated by scripts/gen-schemas.mjs — edit fields to match ADR-004/FEATURES.
